[programs.devnet]
breeding_cooldown = "6znq4tQvjJRwcLRfutp9K5cghLL6zfqJYz7NusVmicYQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
