[programs.devnet]
breeding_cooldown = "83nsodFCXbiRo3gGt6Pz7Bx2Sr1xoxnvm38Bg8CFn7n1"

[provider]
cluster = "devnet"
wallet = "/home/soltyler/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
