[programs.devnet]
breeding_cooldown = "Aijq2XhDqCzSRgUy4JuTw3Sg8VKt7m3Rbm9AFfhSJzTN"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
