[programs.devnet]
breeding_cooldown = "Ajg8yy4gNuLwMWdH1k7sWVNaZb3nMu4wMHY8YED4iY6Y"

[provider]
cluster = "devnet"
wallet = "/Users/chicks1024/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
